### ISSUE TITLE
Line endings written as LF (\n) in Windows host with git bash 

### ISSUE THREAD

**Issue by rcuddy** [devopsgroup-io/vagrant-hostmanager#171]
Host: Windows 7
shell: git-bash 2.6.3.windows.1
terminal: mintty
Running vagrant up with vagrant-hostmanager in a git-bash mintty shell results in the Windows hosts file being written with \n when hostmanager adds entries

``` bash
$ uname -a
MINGW64_NT-6.1 rcuddy-HP 2.3.0(0.290/5/3) 2015-09-29 10:48 x86_64 Msys
```

**Comment by mstra001** [comment]
+1 I can confirm this issue in Windows 10, this seems to be fixed in vagrant-hostsupdater
https://github.com/cogitatio/vagrant-hostsupdater/commit/714d4b91b1e7999338b68af8df060610fc15efc1

**Comment by masi** [comment]
+1 confirmed on Windows 7

And this is not a nice-to-have, its's a bug. The hosts file on Windows uses \r\n. Vagrant/Hostmanager must not change this. Furthermore it didn't change it in eralier releases, so it's IMHO a regression.

**Comment by bpearson** [comment]
It's a bug, its hard coded to \n in updater.rb but also the old content is changed in Ruby during reading, replacing and writing back out. Check my solution out on #186 .

**Comment by bpearson** [comment]
BTW seen this issue in Windows XP (don't ask) and Windows 10.

**Comment by seth-reeser** [comment]
This is now fixed with v1.8.6

**Comment by danowar2k** [comment]
Nope it isn't fixed (anymore?) in 1.8.9.

* Windows 7
* Vagrant started in git bash

Cause:
* Pathname.read reads the Windows CRLF hosts file and transforms the CRLFs in the file into LF because it "thinks" it should be Unix line endings. This is content A.
* The file content with LF is checked for changes, the new block with LFs is inserted using regex substitution and then the whole file content is changed from LF to CRLF using String.encode on Windows. This results in content B
* Content A and content B is compared using !=
* A has LF, B has CRLF, so they are not equal, so B is saved to file
* Next time hostmanager checks, it reads the hosts file again, converts the CRLF to LF, etc. etc. etc.

This led to two dozen UAC prompts for writing to the system directory containing the hosts file.
